// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: AuctionAudit.proto

package auctionaudit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_BANNER      MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO       MediaType = 2
	MediaType_MEDIA_TYPE_AUDIO       MediaType = 3
	MediaType_MEDIA_TYPE_NATIVE      MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_BANNER",
		2: "MEDIA_TYPE_VIDEO",
		3: "MEDIA_TYPE_AUDIO",
		4: "MEDIA_TYPE_NATIVE",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_BANNER":      1,
		"MEDIA_TYPE_VIDEO":       2,
		"MEDIA_TYPE_AUDIO":       3,
		"MEDIA_TYPE_NATIVE":      4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_AuctionAudit_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_AuctionAudit_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_AuctionAudit_proto_rawDescGZIP(), []int{0}
}

type AuctionError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionError) Reset() {
	*x = AuctionError{}
	mi := &file_AuctionAudit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionError) ProtoMessage() {}

func (x *AuctionError) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionAudit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionError.ProtoReflect.Descriptor instead.
func (*AuctionError) Descriptor() ([]byte, []int) {
	return file_AuctionAudit_proto_rawDescGZIP(), []int{0}
}

func (x *AuctionError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuctionError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type AuctionEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Domain        string                 `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	AppBundle     string                 `protobuf:"bytes,3,opt,name=app_bundle,json=appBundle,proto3" json:"app_bundle,omitempty"`
	MediaTypes    []MediaType            `protobuf:"varint,4,rep,packed,name=media_types,json=mediaTypes,proto3,enum=quicksilver.MediaType" json:"media_types,omitempty"`
	Environment   string                 `protobuf:"bytes,5,opt,name=environment,proto3" json:"environment,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,6,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Errors        []*AuctionError        `protobuf:"bytes,8,rep,name=errors,proto3" json:"errors,omitempty"`
	BidRequest    string                 `protobuf:"bytes,30,opt,name=bid_request,json=bidRequest,proto3" json:"bid_request,omitempty"`
	BidResponse   string                 `protobuf:"bytes,31,opt,name=bid_response,json=bidResponse,proto3" json:"bid_response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionEvent) Reset() {
	*x = AuctionEvent{}
	mi := &file_AuctionAudit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionEvent) ProtoMessage() {}

func (x *AuctionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionAudit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionEvent.ProtoReflect.Descriptor instead.
func (*AuctionEvent) Descriptor() ([]byte, []int) {
	return file_AuctionAudit_proto_rawDescGZIP(), []int{1}
}

func (x *AuctionEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuctionEvent) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuctionEvent) GetAppBundle() string {
	if x != nil {
		return x.AppBundle
	}
	return ""
}

func (x *AuctionEvent) GetMediaTypes() []MediaType {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

func (x *AuctionEvent) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *AuctionEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AuctionEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AuctionEvent) GetErrors() []*AuctionError {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *AuctionEvent) GetBidRequest() string {
	if x != nil {
		return x.BidRequest
	}
	return ""
}

func (x *AuctionEvent) GetBidResponse() string {
	if x != nil {
		return x.BidResponse
	}
	return ""
}

type AuctionFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PartitionId   int32                  `protobuf:"varint,2,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Domain        string                 `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	AppBundle     string                 `protobuf:"bytes,5,opt,name=app_bundle,json=appBundle,proto3" json:"app_bundle,omitempty"`
	MediaTypes    []MediaType            `protobuf:"varint,6,rep,packed,name=media_types,json=mediaTypes,proto3,enum=quicksilver.MediaType" json:"media_types,omitempty"`
	ExpiresAtMs   int64                  `protobuf:"varint,7,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuctionFilterRequest) Reset() {
	*x = AuctionFilterRequest{}
	mi := &file_AuctionAudit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuctionFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuctionFilterRequest) ProtoMessage() {}

func (x *AuctionFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_AuctionAudit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuctionFilterRequest.ProtoReflect.Descriptor instead.
func (*AuctionFilterRequest) Descriptor() ([]byte, []int) {
	return file_AuctionAudit_proto_rawDescGZIP(), []int{2}
}

func (x *AuctionFilterRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

func (x *AuctionFilterRequest) GetPartitionId() int32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *AuctionFilterRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AuctionFilterRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *AuctionFilterRequest) GetAppBundle() string {
	if x != nil {
		return x.AppBundle
	}
	return ""
}

func (x *AuctionFilterRequest) GetMediaTypes() []MediaType {
	if x != nil {
		return x.MediaTypes
	}
	return nil
}

func (x *AuctionFilterRequest) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

var File_AuctionAudit_proto protoreflect.FileDescriptor

const file_AuctionAudit_proto_rawDesc = "" +
	"\n" +
	"\x12AuctionAudit.proto\x12\vquicksilver\"<\n" +
	"\fAuctionError\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x02 \x01(\x05R\x04code\"\xf1\x02\n" +
	"\fAuctionEvent\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06domain\x18\x02 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"app_bundle\x18\x03 \x01(\tR\tappBundle\x127\n" +
	"\vmedia_types\x18\x04 \x03(\x0e2\x16.quicksilver.MediaTypeR\n" +
	"mediaTypes\x12 \n" +
	"\venvironment\x18\x05 \x01(\tR\venvironment\x12!\n" +
	"\ftimestamp_ms\x18\x06 \x01(\x03R\vtimestampMs\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x121\n" +
	"\x06errors\x18\b \x03(\v2\x19.quicksilver.AuctionErrorR\x06errors\x12\x1f\n" +
	"\vbid_request\x18\x1e \x01(\tR\n" +
	"bidRequest\x12!\n" +
	"\fbid_response\x18\x1f \x01(\tR\vbidResponse\"\x8b\x02\n" +
	"\x14AuctionFilterRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\x12!\n" +
	"\fpartition_id\x18\x02 \x01(\x05R\vpartitionId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x16\n" +
	"\x06domain\x18\x04 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"app_bundle\x18\x05 \x01(\tR\tappBundle\x127\n" +
	"\vmedia_types\x18\x06 \x03(\x0e2\x16.quicksilver.MediaTypeR\n" +
	"mediaTypes\x12\"\n" +
	"\rexpires_at_ms\x18\a \x01(\x03R\vexpiresAtMs*\x81\x01\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MEDIA_TYPE_BANNER\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02\x12\x14\n" +
	"\x10MEDIA_TYPE_AUDIO\x10\x03\x12\x15\n" +
	"\x11MEDIA_TYPE_NATIVE\x10\x04BkZ9github.com/prebid/prebid-server/v3/analytics/auctionaudit\xaa\x02-TTD.Markets.QuickSilver.Contract.AuctionAuditb\x06proto3"

var (
	file_AuctionAudit_proto_rawDescOnce sync.Once
	file_AuctionAudit_proto_rawDescData []byte
)

func file_AuctionAudit_proto_rawDescGZIP() []byte {
	file_AuctionAudit_proto_rawDescOnce.Do(func() {
		file_AuctionAudit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_AuctionAudit_proto_rawDesc), len(file_AuctionAudit_proto_rawDesc)))
	})
	return file_AuctionAudit_proto_rawDescData
}

var file_AuctionAudit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_AuctionAudit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_AuctionAudit_proto_goTypes = []any{
	(MediaType)(0),               // 0: quicksilver.MediaType
	(*AuctionError)(nil),         // 1: quicksilver.AuctionError
	(*AuctionEvent)(nil),         // 2: quicksilver.AuctionEvent
	(*AuctionFilterRequest)(nil), // 3: quicksilver.AuctionFilterRequest
}
var file_AuctionAudit_proto_depIdxs = []int32{
	0, // 0: quicksilver.AuctionEvent.media_types:type_name -> quicksilver.MediaType
	1, // 1: quicksilver.AuctionEvent.errors:type_name -> quicksilver.AuctionError
	0, // 2: quicksilver.AuctionFilterRequest.media_types:type_name -> quicksilver.MediaType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_AuctionAudit_proto_init() }
func file_AuctionAudit_proto_init() {
	if File_AuctionAudit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_AuctionAudit_proto_rawDesc), len(file_AuctionAudit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_AuctionAudit_proto_goTypes,
		DependencyIndexes: file_AuctionAudit_proto_depIdxs,
		EnumInfos:         file_AuctionAudit_proto_enumTypes,
		MessageInfos:      file_AuctionAudit_proto_msgTypes,
	}.Build()
	File_AuctionAudit_proto = out.File
	file_AuctionAudit_proto_goTypes = nil
	file_AuctionAudit_proto_depIdxs = nil
}
